### ISSUE TITLE
[META] what pages of the old website have been handled?

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity.org#11]
If successful, all these links should go to some page, either on the new website or somewhere else.

- [x] https://project.yunity.org/values -> https://yunity.atlassian.net/wiki/display/YUN/A+proposal+for+values+of+yunity
- [x] https://project.yunity.org/about_foodsharing -> https://yunity.atlassian.net/wiki/display/YUN/About+foodsharing
- [x] https://project.yunity.org/wuppdays -> https://yunity.atlassian.net/wiki/display/YUN/WuppDays
- [x] https://project.yunity.org/yunity -> /
- [x] https://project.yunity.org/events
- [x] https://project.yunity.org/partner -> https://web.archive.org/web/20170624141249/https://project.yunity.org/partner
- [x] https://project.yunity.org/blog/* -> /heartbeat/*
- [x] https://project.yunity.org/join-the-team -> /imprint
- [x] https://project.yunity.org/build-your-community -> https://yunity.atlassian.net/wiki/display/YUN/Build+your+community
- [x] https://project.yunity.org/foodsaving-worldwide (!! conflicts with new page) -> https://yunity.atlassian.net/wiki/display/FSINT/How+to+build+a+foodsaving+community
- [x] https://project.yunity.org/sharing-community -> https://yunity.atlassian.net/wiki/display/YUN/Tips+for+sharing+communities
- [x] https://project.yunity.org/contributors_2016 (maybe some archive?) -> https://web.archive.org/web/20170624140958/https://project.yunity.org/contributors_2016
- [x] https://project.yunity.org/blog/feed.rss (new feed is at /en/heartbeat.rss )

Old redirects that still get frequent hits, see the logs here: https://project.yunity.org/backend/adrenth/redirect/logs
- [x] https://project.yunity.org/what_we_need (join the team)
- [x] https://project.yunity.org/transparency (to https://yunity.atlassian.net/wiki/display/YUN/Transparency )
- [x] https://project.yunity.org/foodsaving_international (to foodsaving-worldwide)
- [x] https://project.yunity.org/team (to the new empty team page https://project.yunity.org/contributors ) -> 'https://web.archive.org/web/20170624140958/https://project.yunity.org/contributors_2016'

Some blog posts also have old duplicate links.

**Comment by tiltec** [comment]
We can leave the project.yunity.org online as an archive for quite a while, therefore moving the content around is of lesser importance to me.

**Comment by tiltec** [comment]
All redirects live here now: https://github.com/yunity/yunity.org/blob/d9f536df01d9b91218385da63ea5d45e4c660a84/user/config/site.yaml#L112

**Comment by tiltec** [comment]
To Do:

- add aliases to old blog posts (to show at least the english content until we have multilang support)

**Comment by Hardiki** [comment]
Can you elaborate more on this issue? I would like to work on this issue.

**Comment by tiltec** [comment]
This issue became outdated, we seem to have decided to let the old links break and not add multilanguage support to yunity.org
I'll close it.
